### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by shift-reality** [xRubin/unapi-anticaptcha-antigate#1]
Здравствуйте!
А как передать капчу с указанием прокси? Спасибо..

**Comment by xRubin** [comment]
**NoCaptchaTask** в этой библиотеке не реализован, по хорошему надо добавлять новый тип задачи и дополнять декоратор. Но если вам срочно - просто отнаследуйтесь от unapi\anticaptcha\antigate\AntigateService и переопределите метод resolve.

**Comment by xRubin** [comment]
Можно проще. Сделайте свой тип задачи, реализующий AnticaptchaTaskInterface.

class MyTask implements AnticaptchaTaskInterface
{

    public function __construct(array $config = [])
    {
       ... 
      сюда передаете все нужные параметры
       ...
    }
  
    /**
     * @return string[]
     */
    public function asArray(): array
    {
      ... 
     тут их подставляете в необходимом формате
      ....


        return [
           "type" => "NoCaptchaTask",
             "websiteURL" => "http:\/\/mywebsite.com\/recaptcha\/test.php",
            "websiteKey" => "6Lc_aCMTAAAAABx7u2N0D1XnVbI_v6ZdbM6rYf16",
            "proxyType" => "http",
            "proxyAddress" => "8.8.8.8",
            "proxyPort" => 8080,
            "proxyLogin" => "proxyLoginHere",
            "proxyPassword" => "proxyPasswordHere",
            "userAgent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
        ];
    }
}

**Comment by xRubin** [comment]
Набросал NoCaptchaTask, в документацию добавил. Надо бы его погонять с реальными данными.

**Comment by shift-reality** [comment]
Сегодня протестю и отпишусь вам
Спасибо)
